### ISSUE TITLE
EndToEndTest fails for .zip files

### ISSUE THREAD

**Issue by jleyba** [jleyba/js-dossier#39]
```
java.lang.RuntimeException: java.io.IOException: Permission denied
	at com.github.jsdossier.EndToEndTest$1.get(EndToEndTest.java:109)
	at com.github.jsdossier.EndToEndTest$1.get(EndToEndTest.java:103)
	at com.google.common.base.Suppliers$MemoizingSupplier.get(Suppliers.java:125)
	at com.github.jsdossier.EndToEndTest.initOutputDir(EndToEndTest.java:185)
	at sun.reflect.GeneratedMethodAccessor110.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:74)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:211)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
Caused by: java.io.IOException: Permission denied
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createTempFile(File.java:1879)
	at com.sun.nio.zipfs.ZipFileSystem.createTempFileInSameDirectoryAs(ZipFileSystem.java:1087)
	at com.sun.nio.zipfs.ZipFileSystem.sync(ZipFileSystem.java:1190)
	at com.sun.nio.zipfs.ZipFileSystem.close(ZipFileSystem.java:277)
	at com.github.jsdossier.Main.run(Main.java:312)
	at com.github.jsdossier.EndToEndTest.generateData(EndToEndTest.java:140)
	at com.github.jsdossier.EndToEndTest.access$000(EndToEndTest.java:63)
	at com.github.jsdossier.EndToEndTest$1.get(EndToEndTest.java:107)
	... 36 more
```

Using java 1.7.0_25.  Looks related to this [bug with the ZFS](https://bugs.openjdk.java.net/browse/JDK-8004789)

The test passes using 1.8.0_45.

The test should be updated so it passes with JDK7 (which dossier supports).

**Comment by myphysicslab** [comment]
Confirmed that all tests pass and dossier_deploy.jar is being built from just doing ./gendossier.sh.

Used this version:

[09:55:43 ~/Documents/Programming/js-dossier]$ git rev-parse HEAD
61b5b0132a8aba93ab1b10473a889149ec00fdcf
