### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by myphysicslab** [jleyba/js-dossier#78]
I've gotten this a couple or three times now in the last 24 hours.  I'm using the latest version.

```
[17:13:42 ~/Documents/Programming/jssimlab]$ make docs
mkdir -p ./
java -jar ../js-dossier/bazel-bin/src/java/com/github/jsdossier/dossier_deploy.jar -c dossier_config.json
Generating documentation...
[SEVERE][com.github.jsdossier.RenderTaskExecutor] An error occurred
Aug 26, 2016 5:23:51 PM com.github.jsdossier.RenderTaskExecutor$1 onFailure
SEVERE: An error occurred
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.remove(ArrayList.java:865)
	at com.google.javascript.rhino.jstype.UnionTypeBuilder.addAlternate(UnionTypeBuilder.java:283)
	at com.google.javascript.rhino.jstype.UnionTypeBuilder.addAlternate(UnionTypeBuilder.java:315)
	at com.google.javascript.rhino.jstype.JSTypeRegistry.registerPropertyOnType(JSTypeRegistry.java:655)
	at com.google.javascript.rhino.jstype.ObjectType.defineDeclaredProperty(ObjectType.java:299)
	at com.google.javascript.rhino.jstype.RecordType.<init>(RecordType.java:95)
	at com.google.javascript.rhino.jstype.RecordTypeBuilder.build(RecordTypeBuilder.java:92)
	at com.google.javascript.rhino.jstype.JSTypeRegistry.createRecordTypeFromNodes(JSTypeRegistry.java:1755)
	at com.google.javascript.rhino.jstype.JSTypeRegistry.createFromTypeNodesInternal(JSTypeRegistry.java:1528)
	at com.google.javascript.rhino.jstype.JSTypeRegistry.createTypeFromCommentNode(JSTypeRegistry.java:1521)
	at com.google.javascript.rhino.JSTypeExpression.evaluate(JSTypeExpression.java:100)
	at com.github.jsdossier.RenderDocumentationTaskSupplier$NominalTypeProcessor.addTypedefInfo(RenderDocumentationTaskSupplier.java:356)
	at com.github.jsdossier.RenderDocumentationTaskSupplier$NominalTypeProcessor.buildJsType(RenderDocumentationTaskSupplier.java:228)
	at com.github.jsdossier.RenderDocumentationTaskSupplier$2.get(RenderDocumentationTaskSupplier.java:103)
	at com.github.jsdossier.RenderDocumentationTaskSupplier$2.get(RenderDocumentationTaskSupplier.java:98)
	at com.google.common.base.Suppliers$MemoizingSupplier.get(Suppliers.java:123)
	at com.github.jsdossier.RenderDocumentationTaskSupplier$RenderDocumentationTask.call(RenderDocumentationTaskSupplier.java:147)
	at com.github.jsdossier.RenderDocumentationTaskSupplier$RenderDocumentationTask.call(RenderDocumentationTaskSupplier.java:118)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:113)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:59)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:74)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Exception in thread "main" java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.remove(ArrayList.java:865)
	at com.google.javascript.rhino.jstype.UnionTypeBuilder.addAlternate(UnionTypeBuilder.java:283)
	at com.google.javascript.rhino.jstype.UnionTypeBuilder.addAlternate(UnionTypeBuilder.java:315)
	at com.google.javascript.rhino.jstype.JSTypeRegistry.registerPropertyOnType(JSTypeRegistry.java:655)
	at com.google.javascript.rhino.jstype.ObjectType.defineDeclaredProperty(ObjectType.java:299)
	at com.google.javascript.rhino.jstype.RecordType.<init>(RecordType.java:95)
	at com.google.javascript.rhino.jstype.RecordTypeBuilder.build(RecordTypeBuilder.java:92)
	at com.google.javascript.rhino.jstype.JSTypeRegistry.createRecordTypeFromNodes(JSTypeRegistry.java:1755)
	at com.google.javascript.rhino.jstype.JSTypeRegistry.createFromTypeNodesInternal(JSTypeRegistry.java:1528)
	at com.google.javascript.rhino.jstype.JSTypeRegistry.createTypeFromCommentNode(JSTypeRegistry.java:1521)
	at com.google.javascript.rhino.JSTypeExpression.evaluate(JSTypeExpression.java:100)
	at com.github.jsdossier.RenderDocumentationTaskSupplier$NominalTypeProcessor.addTypedefInfo(RenderDocumentationTaskSupplier.java:356)
	at com.github.jsdossier.RenderDocumentationTaskSupplier$NominalTypeProcessor.buildJsType(RenderDocumentationTaskSupplier.java:228)
	at com.github.jsdossier.RenderDocumentationTaskSupplier$2.get(RenderDocumentationTaskSupplier.java:103)
	at com.github.jsdossier.RenderDocumentationTaskSupplier$2.get(RenderDocumentationTaskSupplier.java:98)
	at com.google.common.base.Suppliers$MemoizingSupplier.get(Suppliers.java:123)
	at com.github.jsdossier.RenderDocumentationTaskSupplier$RenderDocumentationTask.call(RenderDocumentationTaskSupplier.java:147)
	at com.github.jsdossier.RenderDocumentationTaskSupplier$RenderDocumentationTask.call(RenderDocumentationTaskSupplier.java:118)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:113)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:59)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:74)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
make: *** [docs] Error 1
```

**Comment by jleyba** [comment]
While I track this down, you can avoid the error by running with `--num_threads=1`
