### ISSUE TITLE
cannot build js-dossier

### ISSUE THREAD

**Issue by myphysicslab** [jleyba/js-dossier#95]
I just checked out the current version of js-dossier, now getting the following errors:

```
[10:52:27 ~/Documents/Programming/js-dossier]$ ./gendossier.sh 
..........
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
ERROR: /Users/erikn/Documents/Programming/js-dossier/build_tools/js_binary.bzl:30:21: Traceback (most recent call last):
	File "/Users/erikn/Documents/Programming/js-dossier/build_tools/js_binary.bzl", line 27
		rule(implementation = _js_binary_impl, <2 more arguments>)
	File "/Users/erikn/Documents/Programming/js-dossier/build_tools/js_binary.bzl", line 30, in rule
		attr.label(default = Label("//lib/maven:Clo..."), <2 more arguments>)
expected ConfigurationTransition or NoneType for 'cfg' while calling label but got string instead: host.
SLF4J: The following set of substitute loggers may have been accessed
SLF4J: during the initialization phase. Logging calls during this
SLF4J: phase were not honored. However, subsequent logging calls to these
SLF4J: loggers will work as normally expected.
SLF4J: See also http://www.slf4j.org/codes.html#substituteLogger
SLF4J: org.eclipse.aether.internal.impl.DefaultRepositorySystem
ERROR: /Users/erikn/Documents/Programming/js-dossier/src/java/com/github/jsdossier/BUILD:1:1: error loading package 'src/js': Extension file 'build_tools/js_binary.bzl' has errors and referenced by '//src/java/com/github/jsdossier:jsdossier'.
ERROR: Loading failed; build aborted.
INFO: Elapsed time: 2.260s
ERROR: Couldn't start the build. Unable to run tests.
```

This shows what version I'm compiling:

```
[10:52:50 ~/Documents/Programming/js-dossier]$ git log
commit 0b32330c53b68d6cff6aa32b1e4655cf7b02039b
Author: Jason Leyba <jmleyba@gmail.com>
Date:   Tue Dec 20 08:12:43 2016 -0800

    More code cleanup
```

Previous to this I was able to build.

**Comment by myphysicslab** [comment]
I figured out I need bazel 0.4.  Now Dossier is building, but it's not making any docs for my project, probably because some Dossier API has changed.  But I'll investigate and open another issue on that if needed.
