### ISSUE TITLE
unit test nav_test is failing

### ISSUE THREAD

**Issue by myphysicslab** [jleyba/js-dossier#98]
The unit test at `test/js/nav_test.html` fails when opening with Safari browser on Mac OS.  The other two unit tests there, `heap_test` and `search_test` are succeeding.  The error is

```
dossier.nav.test [FAILED]

12:04:50.352  Start
12:04:50.354  testBuildTree_attachesNestedClassesToParentNamespace : FAILED (run individually)
12:04:50.354  ERROR in testBuildTree_attachesNestedClassesToParentNamespace
Can't find variable: Arrays
> (unknown)
> (unknown)
> (unknown)
> (unknown)
> (unknown)
> testBuildTree_attachesNestedClassesToParentNamespace at file:///Users/erikn/Documents/Programming/js-dossier/test/js/nav_test.js:182:27
> (unknown)
> invokeTestFunction_ at file:///Users/erikn/Documents/Programming/js-dossier/third_party/js/closure_library/closure/goog/testing/testcase.js:853:25
> safeRunTest_ at file:///Users/erikn/Documents/Programming/js-dossier/third_party/js/closure_library/closure/goog/testing/testcase.js:803:27
> invokeTestFunction_ at file:///Users/erikn/Documents/Programming/js-dossier/third_party/js/closure_library/closure/goog/testing/testcase.js:879:23
> runNextTest_ at file:///Users/erikn/Documents/Programming/js-dossier/third_party/js/closure_library/closure/goog/testing/testcase.js:793:27
> (unknown)
> Promise at file:///Users/erikn/Documents/Programming/js-dossier/third_party/js/closure_library/closure/goog/promise/promise.js:164:20
> runTestsReturningPromise at file:///Users/erikn/Documents/Programming/js-dossier/third_party/js/closure_library/closure/goog/testing/testcase.js:757:26
> execute at file:///Users/erikn/Documents/Programming/js-dossier/third_party/js/closure_library/closure/goog/testing/testrunner.js:264:43
> (unknown)
```
If I substitute `goog.array` for `Arrays` in the file `src/js/nav.js` the test proceeds past that error, but some similar errors occur on other names.  With similar substitutions, the test succeeds.  Specifically these substitutions:
```
Arrays --> goog.array
Index --> proto.dossier.Index
NamedType --> proto.dossier.expression.NamedType
```
Does the `deps.js` file need to be regenerated?  Or is there some missing magic about using `goog.module` and `goog.require`?

**Comment by myphysicslab** [comment]
Now that closure-library is no longer in the repository because of commit f0e495c6fa656e66a2535000699823b7a2a2e8bc, all of these unit tests at `test/js/` are no longer working.
